/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bb-green': {
          50: '#E8F5E9',
          100: '#C8E6C9',
          200: '#A5D6A7',
          300: '#81C784',
          400: '#66BB6A',
          500: '#4CAF50',
          600: '#43A047',
          700: '#388E3C',
          800: '#2E7D32',
          900: '#1B5E20',
        },
        'bb-dark': {
          50: '#1a2332',
          100: '#151d2a',
          200: '#111822',
          300: '#0d131b',
          400: '#0a0f15',
          500: '#070b10',
          600: '#05080c',
          700: '#030508',
          800: '#020305',
          900: '#010203',
        },
        'bb-light': {
          50: '#ffffff',
          100: '#f8fafc',
          200: '#f1f5f9',
          300: '#e2e8f0',
          400: '#cbd5e1',
          500: '#94a3b8',
          600: '#64748b',
          700: '#475569',
          800: '#334155',
          900: '#1e293b',
        },
        'bb-accent': '#00E676',
        'bb-accent-dark': '#00C853',
        'bb-teal': '#00BFA5',
        'bb-mint': '#69F0AE',
        'bb-cyan': '#00E5FF',
        'bb-purple': '#7C4DFF',
      },
      fontFamily: {
        'mono': ['JetBrains Mono', 'Fira Code', 'monospace'],
        'sans': ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'scan': 'scan 3s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up': 'slide-up 0.6s ease-out',
        'slide-down': 'slide-down 0.4s ease-out',
        'fade-in': 'fade-in 0.5s ease-out',
        'scale-in': 'scale-in 0.3s ease-out',
        'spin-slow': 'spin 8s linear infinite',
        'border-flow': 'border-flow 3s linear infinite',
        'gradient-text': 'gradient-text 4s ease infinite',
        'count-up': 'count-up 0.4s ease-out',
        'shine-sweep': 'shine-sweep 3s ease-in-out infinite',
        'particle-float': 'particle-float 8s ease-in-out infinite',
        'particle-float-2': 'particle-float-2 10s ease-in-out infinite',
        'particle-float-3': 'particle-float-3 12s ease-in-out infinite',
        'hex-spin': 'hex-spin 20s linear infinite',
        'hex-spin-reverse': 'hex-spin 25s linear infinite reverse',
        'wave': 'wave 8s ease-in-out infinite',
        'spotlight': 'spotlight 4s ease-in-out infinite',
        'glitch-1': 'glitch-1 0.3s ease-in-out',
        'glitch-2': 'glitch-2 0.3s ease-in-out 0.1s',
        'tilt-in': 'tilt-in 0.6s ease-out',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'progress-fill': 'progress-fill 1s ease-out',
        'border-glow': 'border-glow 2s ease-in-out infinite',
        'scroll-indicator': 'scroll-indicator 2s ease-in-out infinite',
        'morphing-bg': 'morphing-bg 15s ease-in-out infinite',
        'stagger-in': 'stagger-in 0.5s ease-out both',
        'row-enter': 'row-enter 0.4s ease-out both',
        'crown-bounce': 'crown-bounce 2s ease-in-out infinite',
        'sparkle': 'sparkle 1.5s ease-in-out infinite',
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'scan': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'shimmer': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.8)', opacity: '1' },
          '50%': { transform: 'scale(1.2)', opacity: '0' },
          '100%': { transform: 'scale(0.8)', opacity: '0' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'border-flow': {
          '0%, 100%': { 'background-position': '0% 50%' },
          '50%': { 'background-position': '100% 50%' },
        },
        'gradient-text': {
          '0%, 100%': { 'background-position': '0% 50%' },
          '50%': { 'background-position': '100% 50%' },
        },
        'shine-sweep': {
          '0%': { transform: 'translateX(-100%) skewX(-15deg)' },
          '100%': { transform: 'translateX(200%) skewX(-15deg)' },
        },
        'particle-float': {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)', opacity: '0.3' },
          '25%': { transform: 'translate(30px, -40px) rotate(90deg)', opacity: '0.6' },
          '50%': { transform: 'translate(-20px, -80px) rotate(180deg)', opacity: '0.3' },
          '75%': { transform: 'translate(40px, -40px) rotate(270deg)', opacity: '0.5' },
        },
        'particle-float-2': {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)', opacity: '0.2' },
          '33%': { transform: 'translate(-40px, -60px) rotate(120deg)', opacity: '0.5' },
          '66%': { transform: 'translate(20px, -100px) rotate(240deg)', opacity: '0.3' },
        },
        'particle-float-3': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)', opacity: '0.2' },
          '25%': { transform: 'translate(50px, -30px) scale(1.2)', opacity: '0.4' },
          '50%': { transform: 'translate(-30px, -70px) scale(0.8)', opacity: '0.6' },
          '75%': { transform: 'translate(20px, -50px) scale(1.1)', opacity: '0.3' },
        },
        'hex-spin': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'wave': {
          '0%, 100%': { transform: 'translateY(0)', opacity: '0.5' },
          '50%': { transform: 'translateY(-5px)', opacity: '1' },
        },
        'spotlight': {
          '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
          '50%': { opacity: '0.6', transform: 'scale(1.1)' },
        },
        'glitch-1': {
          '0%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-3px, 3px)' },
          '40%': { transform: 'translate(-3px, -3px)' },
          '60%': { transform: 'translate(3px, 3px)' },
          '80%': { transform: 'translate(3px, -3px)' },
          '100%': { transform: 'translate(0)' },
        },
        'glitch-2': {
          '0%': { transform: 'translate(0)', opacity: '0.8' },
          '20%': { transform: 'translate(3px, -3px)', opacity: '0.6' },
          '40%': { transform: 'translate(3px, 3px)', opacity: '0.8' },
          '60%': { transform: 'translate(-3px, -3px)', opacity: '0.6' },
          '80%': { transform: 'translate(-3px, 3px)', opacity: '0.8' },
          '100%': { transform: 'translate(0)', opacity: '0.8' },
        },
        'tilt-in': {
          '0%': { transform: 'perspective(500px) rotateX(10deg)', opacity: '0' },
          '100%': { transform: 'perspective(500px) rotateX(0deg)', opacity: '1' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0, 230, 118, 0.2), 0 0 10px rgba(0, 230, 118, 0.1)' },
          '50%': { boxShadow: '0 0 15px rgba(0, 230, 118, 0.4), 0 0 30px rgba(0, 230, 118, 0.2)' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'progress-fill': {
          '0%': { width: '0%' },
          '100%': { width: 'var(--progress-width)' },
        },
        'border-glow': {
          '0%, 100%': { borderColor: 'rgba(0, 230, 118, 0.2)' },
          '50%': { borderColor: 'rgba(0, 230, 118, 0.5)' },
        },
        'scroll-indicator': {
          '0%, 100%': { transform: 'translateY(0)', opacity: '0.5' },
          '50%': { transform: 'translateY(4px)', opacity: '1' },
        },
        'morphing-bg': {
          '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
          '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
        },
        'stagger-in': {
          '0%': { opacity: '0', transform: 'translateY(15px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'row-enter': {
          '0%': { opacity: '0', transform: 'translateX(-8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'crown-bounce': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '25%': { transform: 'translateY(-3px) rotate(-5deg)' },
          '75%': { transform: 'translateY(-3px) rotate(5deg)' },
        },
        'sparkle': {
          '0%, 100%': { opacity: '0', transform: 'scale(0) rotate(0deg)' },
          '50%': { opacity: '1', transform: 'scale(1) rotate(180deg)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
